In [39]:
import numpy as np
import numpy
import torch.nn as nn

import argparse

import os
import numpy as np
import torch
from PIL import Image

import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor

from engine import train_one_epoch, evaluate
import utils
import transforms as T
import time

import os
import numpy as np
import torch
from PIL import Image
import torch.nn as nn

import torchvision
from torchvision.models.detection.faster_rcnn import FastRCNNPredictor
from torchvision.models.detection.mask_rcnn import MaskRCNNPredictor
from torchsummary import summary

from engine import train_one_epoch, evaluate
import utils
import transforms as T

import matplotlib.pyplot as plt
import matplotlib

matplotlib.use('TkAgg')

In [40]:
def get_transform(train):
    transforms = []
    transforms.append(T.ToTensor())
    if train:
        transforms.append(T.RandomHorizontalFlip(0.5))
    return T.Compose(transforms)

In [41]:
def get_model_instance_segmentation(num_classes):
    # load an instance segmentation model pre-trained pre-trained on COCO
    model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True)
    model.backbone.body.conv1 = nn.Conv2d(7, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)

    # get number of input features for the classifier
    in_features = model.roi_heads.box_predictor.cls_score.in_features
    # replace the pre-trained head with a new one
    model.roi_heads.box_predictor = FastRCNNPredictor(in_features, num_classes)

    # now get the number of input features for the mask classifier
    in_features_mask = model.roi_heads.mask_predictor.conv5_mask.in_channels
    hidden_layer = 256
    # and replace the mask predictor with a new one
    model.roi_heads.mask_predictor = MaskRCNNPredictor(in_features_mask,
                                                       hidden_layer,
                                                       num_classes)

    return model

In [42]:
def load_all_label(path):
    replay_name = path.split('/')[-2]
    label_path = path.replace(replay_name + "/", '')
    label_len = len(os.listdir(label_path + replay_name +"/"))
    labels = np.array([])
    for i in range(0, label_len):
        labels = np.append(labels, np.load(label_path + replay_name +"/"+ str(i) + ".npy", allow_pickle=True)[1])

    results = labels

    return results

In [43]:
class PennFudanDataset(object):
    def __init__(self, path, transforms, window_size):
        self.root = path
        self.transforms = transforms
        pth = os.listdir(path)
        self.label_sequences = []

        self.dir_paths = []
        for i in pth:
            if os.path.isdir(path + i):
                self.label_sequences += [load_all_label(path + i +'/')]
                self.dir_paths.append(path + i + '/')
                print(f"Loaded {i}")

        self.window_size = window_size

        self.seq_indexs = []
        start = 0
        for i, seq in enumerate(self.label_sequences):
            end = start + len(seq) - (self.window_size - 1)
            self.seq_indexs.append((i, start, end))
            start = end

    def __len__(self):
        return self.seq_indexs[-1][-1]

    def __getitem__(self, idx):
        # load images and masks
        for i, start, end in self.seq_indexs:
            if idx >= start and idx < end:
                real_idx = idx - start

                data = np.load(self.dir_paths[i] + '/' + str(real_idx) + ".npy", allow_pickle=True)[0][0]    # (11, 128, 128)
                masks = np.load(self.dir_paths[i] + '/' + str(real_idx) + ".npy", allow_pickle=True)[1][0]   #  (128, 128)
                masks = np.expand_dims(masks, axis=0)
                break

        input_data = self.preprocessing(data)


        num_objs = 1
        boxes = []
        for i in range(num_objs):
            pos = np.where(masks[i])
            xmin = np.min(pos[1])
            xmax = np.max(pos[1])
            ymin = np.min(pos[0])
            ymax = np.max(pos[0])
            boxes.append([xmin, ymin, xmax, ymax])

        boxes = torch.as_tensor(boxes, dtype=torch.float32)
        # there is only one class
        labels = torch.ones((num_objs,), dtype=torch.int64)
        masks = torch.as_tensor(masks, dtype=torch.uint8)

        image_id = torch.tensor([idx])
        area = (boxes[:, 3] - boxes[:, 1]) * (boxes[:, 2] - boxes[:, 0])
        # suppose all instances are not crowd
        iscrowd = torch.zeros((num_objs,), dtype=torch.int64)

        target = {}
        target["boxes"] = boxes
        target["labels"] = labels
        target["masks"] = masks
        target["image_id"] = image_id
        target["area"] = area
        target["iscrowd"] = iscrowd

        return input_data, target


    def preprocessing(self, data):
        #0 ground 1 air 2 building 3 spell 4 ground 5 air 6 building 7 spell 8 resource 9 vision 10 terrain
        temp = np.zeros([self.window_size, 7, data.shape[2],data.shape[2]])

        temp[:,0] = data[0]
        temp[:,1] = data[1]
        temp[:,2] = data[2]
        temp[:,3] = data[4]
        temp[:,4] = data[5]
        temp[:,5] = data[6]
        temp[:,6] = data[9]

        data = temp
        data = data.reshape(self.window_size*data.shape[1],data.shape[2],-1)
        
        return torch.FloatTensor(data)    

In [105]:
import sys
data_path = f"./test_data2/"
# dataset = PennFudanDataset(data_path, get_transform(train=False), window_size=1)
dataset_test = PennFudanDataset(data_path, get_transform(train=False),window_size=1)

Loaded 36


In [159]:
len(dataset_test)

3541

In [155]:
# 수집한 데이터 중 1개에 대한 인풋, 아웃풋(정답) Plotting
index=0
img_t, target_t = dataset_test[index]
print("img_t.shape: ", img_t.shape)
img_total = img_t.sum(axis=0, keepdim=True)
plt.subplot(2,1,1)
plt.imshow(img_total[0].mul(255).byte().detach().numpy())
plt.subplot(2,1,2)
plt.imshow(target_t['masks'][0].mul(255).byte().detach().numpy().T)
plt.show()

img_t.shape:  torch.Size([7, 128, 128])


In [157]:
target_t['masks'][0]

tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0],
        [0, 0, 1,  ..., 0, 0, 0]], dtype=torch.uint8)

In [156]:
target_t['boxes'][0]

tensor([  2., 108.,  13., 127.])

In [158]:
target_t['boxes'][0]*32

tensor([  64., 3456.,  416., 4064.])

In [160]:
# 데이터 셋 샘플링 or Plotting
# Start, End, Step = 200, 205, 1
Start, End, Step = 0, 3451, 1
test_img_array = []
test_img_one_channel_array = []
test_target_array = []
for i in range(Start,End,Step):
    img_t, target_t = dataset_test[i]
    test_img_array.append(img_t)
    img_one_channel = img_t.sum(axis=0, keepdim=True)
    test_img_one_channel_array.append(img_one_channel)
    test_target_array.append(target_t)

In [84]:
#plot_len = int(len(test_img_array)/2)
#for i in range(plot_len):
#    plt.subplot(2,plot_len,i+1)
#    plt.imshow(test_img_one_channel_array[i][0].mul(255).byte().detach().numpy().T)
#    plt.subplot(2,plot_len,i+1+plot_len)
#    plt.imshow(test_target_array[i]['masks'][0].mul(255).byte().detach().numpy().T)
#plt.show()

In [161]:
# 학습 후 prediction 출력
num_classes = 2
model = get_model_instance_segmentation(num_classes)
model.load_state_dict(torch.load("saved_models/model_10.pth"))
model.eval()
with torch.no_grad():
    prediction = model(test_img_array)

RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:76] data. DefaultCPUAllocator: not enough memory: you tried to allocate 17920000 bytes.

In [152]:
# 인풋, 정답, prediction에 대한 Plotting
plot_len = int(len(test_img_array)/2)
for i in range(plot_len):
    plt.subplot(3,plot_len,i+1)
    plt.imshow(test_img_one_channel_array[i][0].mul(255).byte().detach().numpy())
    plt.subplot(3,plot_len,i+1+ plot_len)
    plt.imshow(test_target_array[i]['masks'][0].mul(255).byte().detach().numpy().T)
    plt.subplot(3,plot_len,i+1+ plot_len*2)
    #plt.imshow(prediction[i]['masks'][3].sum(axis=0).mul(255).byte().detach().numpy().T)
    plt.imshow(prediction[i]['masks'][0].sum(axis=0).mul(255).byte().detach().numpy().T)
plt.show()

In [119]:
test_target_array[0]["labels"]

tensor([1])

In [147]:
test_target_array[0]["masks"].max()

tensor(1, dtype=torch.uint8)

In [151]:
test_target_array[1]["boxes"][0]

tensor([110., 108., 121., 127.])

In [150]:
prediction[1]['boxes'][0]

tensor([109.4481, 108.0071, 120.7171, 127.0499])

In [129]:
test_target_array[5]["boxes"]

tensor([[ 85.,  97.,  96., 116.]])

In [114]:
target_t.keys()

dict_keys(['boxes', 'labels', 'masks', 'image_id', 'area', 'iscrowd'])

In [116]:
target_t["masks"].shape

torch.Size([1, 128, 128])

In [92]:
prediction[0]['masks'].shape

torch.Size([9, 1, 128, 128])

In [95]:
prediction[0]['labels']

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [87]:
prediction[0].keys()

dict_keys(['boxes', 'labels', 'scores', 'masks'])

In [88]:
prediction[0]["boxes"]

tensor([[ 34.7093,  18.5101,  45.5739,  37.2065],
        [ 33.0960,   6.5159,  44.1429,  26.0190],
        [  3.7773,   0.0000,  14.8168,  19.0350],
        [107.0917, 108.0264, 117.6414, 127.2897],
        [112.9700, 107.5525, 123.7498, 126.9076],
        [ 92.0005,  21.8149, 102.9863,  40.7442],
        [ 89.0254, 102.6754,  99.9427, 121.4857],
        [ 32.3551,  28.2777,  36.7931,  36.8388],
        [  2.1496, 108.0664,  13.0492, 127.0174]])

In [89]:
len(prediction[0]["boxes"])

9

In [94]:
prediction[0]['labels'].shape

torch.Size([9])

In [102]:
prediction[0]['scores']

tensor([0.9776, 0.6844, 0.4229, 0.3269, 0.1007, 0.0929, 0.0864, 0.0803, 0.0715])